apiVersion: v1
data:
  KAFKA_ADDRESS: kafkaserver:9092
  KAFKA_GROUP_ID: user-service-group
  KAFKA_TOPIC_1: user-topic
  KAFKA_TOPIC_2: response-user-topic
  UM_DATASOURCE_HOST: user-service-db
  DATASOURCE_PORT: "3306"
kind: ConfigMap
metadata:
  name: user-service-env-file
---
apiVersion: v1
data:
  CM_DATASOURCE_HOST: catalog-service-db
  KAFKA_ADDRESS: kafkaserver:9092
  KAFKA_GROUP_ID: catalog-service-group
  KAFKA_TOPIC_3: payment-topic
  KAFKA_TOPIC_4: response-payment-topic
  DATASOURCE_PORT: "3306"
kind: ConfigMap
metadata:
  name: catalog-service-env-file
---
apiVersion: v1
data:
  PM_DATASOURCE_HOST: pay-service-db
  KAFKA_ADDRESS: kafkaserver:9092
  KAFKA_GROUP_ID: pay-service-group
  KAFKA_TOPIC_1: user-topic
  KAFKA_TOPIC_2: response-user-topic
  KAFKA_TOPIC_3: payment-topic
  KAFKA_TOPIC_4: response-payment-topic
  DATASOURCE_PORT: "3306"
kind: ConfigMap
metadata:
  name: pay-service-env-file

